.PHONY: package

package:
	go mod tidy
	cfn generate
	env CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -tags="logging callback scheduler" -o bin/handler cmd/main.go
	env CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bin/k8svpc vpc/main.go
	cd bin ; zip k8svpc.zip k8svpc ; rm k8svpc ; cd ..
	cfn submit --verbose --dry-run
